version: '3'
services:
  wordpress:
    image: {{APP_IMAGE_NAME_TAG}}
    env_file:
      - .env
    ports:
      - ${HOST_PORT:-3000}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_SITEURL', '${SERVER_URL}' );
        define('WP_HOME', '${SERVER_URL}' );
        define('FORCE_SSL_ADMIN', true);
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-{{OIDC_CLIENT_ID}}}
      OIDC_ENDPOINT_LOGIN_URL: ${OIDC_ENDPOINT_LOGIN_URL:-{{OIDC_ENDPOINT_LOGIN_URL}}}
      OIDC_ENDPOINT_USERINFO_URL: ${OIDC_ENDPOINT_USERINFO_URL:-{{OIDC_ENDPOINT_USERINFO_URL}}}
      OIDC_ENDPOINT_TOKEN_URL: ${OIDC_ENDPOINT_TOKEN_URL:-{{OIDC_ENDPOINT_TOKEN_URL}}}
      OIDC_ENDPOINT_LOGOUT_URL: ${OIDC_ENDPOINT_LOGOUT_URL:-{{OIDC_ENDPOINT_LOGOUT_URL}}}
      OIDC_CLIENT_SCOPE: ${OIDC_CLIENT_SCOPE:-{{OIDC_CLIENT_SCOPE}}}
      OIDC_LOGIN_TYPE: ${OIDC_LOGIN_TYPE:-{{OIDC_LOGIN_TYPE}}}
      OIDC_CREATE_IF_DOES_NOT_EXIST: ${OIDC_CREATE_IF_DOES_NOT_EXIST:-{{OIDC_CREATE_IF_DOES_NOT_EXIST}}}
      OIDC_LINK_EXISTING_USERS: ${OIDC_LINK_EXISTING_USERS:-{{OIDC_LINK_EXISTING_USERS}}}
      OIDC_REDIRECT_USER_BACK: ${OIDC_REDIRECT_USER_BACK:-{{OIDC_REDIRECT_USER_BACK}}}
      OIDC_ENFORCE_PRIVACY: ${OIDC_ENFORCE_PRIVACY:-{{OIDC_ENFORCE_PRIVACY}}}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - uploads-data:{{WP_UPLOADS_DIR}}
      - wp-logs-data:{{WP_LOG_ROOT}}

  init:
    image: {{APP_UTILS_IMAGE_NAME_TAG}}
    env_file:
      - .env
    environment:
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-{{GC_BUCKET_BACKUPS}}}
      GC_PROJECT: ${GC_PROJECT:-{{GC_PROJECT}}}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-{{BACKUP_FILE_NAME}}}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-{{UPLOADS_FILE_NAME}}}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./gc-reader-key.json:/etc/service-account.json
    command: ./init/init.sh

  backup:
    image: {{APP_UTILS_IMAGE_NAME_TAG}}
    env_file:
      - .env
    environment:
      GC_BUCKET_BACKUPS: ${GC_BUCKET_BACKUPS:-{{GC_BUCKET_BACKUPS}}}
      BACKUP_FILE_NAME: ${BACKUP_FILE_NAME:-{{BACKUP_FILE_NAME}}}
      UPLOADS_FILE_NAME: ${UPLOADS_FILE_NAME:-{{UPLOADS_FILE_NAME}}}
      WORDPRESS_DB_HOST: ${DB_HOST:-db:3306}
    depends_on:
      - db
      - wordpress
    volumes:
      - uploads-data:/uploads
      - ./gc-writer-key.json:/etc/service-account.json
    command: "./backup/entrypoint.sh"

  db:
    image: {{MYSQL_IMAGE_NAME_TAG}}
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 262114
        hard: 262114

volumes:
  db-data:
  uploads-data:
  wp-logs-data:
